Task/bws37 private routes
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #12
Opened 2022-02-08 09:40 UTC by sofia0602

2022-02-08 09:46 UTC, Donymak commented on backend/package.json
> +    "@types/bcrypt": "^5.0.0",
Check [B19](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md#rubbish) criteria

2022-02-08 10:03 UTC, Donymak commented on package.json
> +    "bcrypt": "^5.0.1",
Check [B19](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md#rubbish) criteria

2022-02-08 10:12 UTC, Donymak reviewed
To save exact version of the package use 
`nmp i --save --save-exact <module_name>` for packages and
`nmp i --save --save-dev --save-exact <module_type_name>` for types

2022-02-08 10:35 UTC, what1s1ove requested changes

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +      </ul>
```suggestion
```

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +        />
```suggestion
        <PrivateRoute
          path={AppRoute.ROOT}
          element={<Dashboard />}
        />
```
it should be in this way

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/auth/auth.tsx
> +    navigate(AppRoute.ROOT, { replace: true });
```suggestion
```
what to do if an error occurs?
we should do this logic in the action. Create a history service for it

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/auth/components/home.tsx
> +import { FC } from 'react';
this page in the auth scope. we need to avoid it

move it to the frontend/src/components/dashboard/dashboard.tsx

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/auth/components/home.tsx
> +export { Home };
```suggestion
const Dashboard: FC = () => {
  return <>HOME</>;
};
export { Dashboard };
```

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/auth/hoc/private-route.tsx
> +import { Navigate, useAppSelector, useLocation } from 'hooks/hooks';
move it to the `frontend/src/components/common/private-route/private-route.tsx`

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/auth/hoc/private-route.tsx
> +function PrivateRoute({ children }: Props): JSX.Element {
use arrow function

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/components/auth/hoc/private-route.tsx
> +  );
should be something like this
```tsx
import { RouteProps } from 'react-router-dom';

type Props = RouteProps & {
  redirectTo?: AppRoute;
};

const PrivateRoute: React.FC<Props> = ({
  redirectTo = AppRoute.SIGN_IN,
  ...otherProps
}) => {
  const { user } = useAppSelector(({ auth }) => ({
    user: auth.user,
  }));

  const hasUser = Boolean(user);

  if (!hasUser) {
    return <Navigate to={redirectTo} />;
  }

  return // return origin component;
};
\
```

2022-02-08 10:35 UTC, what1s1ove commented on frontend/src/hooks/hooks.ts
> +  Navigate,
Navigate isn't a hook

2022-02-08 10:35 UTC, what1s1ove commented on package.json
> +    "bcrypt": "^5.0.1",
we don't need it in the root folder

2022-02-08 10:36 UTC, what1s1ove requested changes

2022-02-08 10:36 UTC, what1s1ove commented on backend/package-lock.json
> +        "@types/bcrypt": "^5.0.0",
this file shouldn't be changed

2022-02-09 06:34 UTC, what1s1ove requested changes

2022-02-09 06:34 UTC, what1s1ove commented on backend/package-lock.json
> +        "@types/bcrypt": "^5.0.0",
don't fixed

2022-02-09 06:34 UTC, what1s1ove commented on package.json
> +    "bcrypt": "5.0.1",
remove it from the root packages

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/store/navigation/reducer.ts
> +import { createReducer } from '@reduxjs/toolkit';
we don't need navigation reducer

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/store/auth/reducer.ts
> +  user: { email: '', id: '' },
```suggestion
  user: MasterDto | null;
};

const initialState: State = {
  dataStatus: DataStatus.IDLE,
  user: null,
```

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/store/store.ts
> +  history,
imports?

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/components/auth/auth.tsx
> +    dispatch(navigationActions.pushHistory(fromPage));
```suggestion
  const handleSignUpSubmit = (payload: MasterSignUpRequestDto): void => {
    dispatch(authActions.signUp(payload));
```

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/components/auth/auth.tsx
> +import { navigation as navigationActions } from 'store/actions';
```suggestion
```

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +      </ul>
remove it

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/services/services.ts
> +import { createBrowserHistory } from 'history';
import order. packages should be first

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/store/auth/actions.ts
> +    return user;
```suggestion
    const { authAp } = extra;
    const user: MasterDto = await authApi.signUp(registerPayload);
```

2022-02-09 06:34 UTC, what1s1ove commented on frontend/src/components/auth/auth.tsx
>    };
```tsx
  const { user } = useAppSelector(({ auth }) => ({
    user: auth.user,
  }));

const hasUser = Boolean(user);

  if (hasUser) {
    return <Navigate to={redirectTo} />;
  }
```

2022-02-09 09:20 UTC, what1s1ove requested changes

2022-02-09 09:20 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +import { PrivateRoute } from 'components/common/private-route/private-route';
```suggestion
import { Routes, Route, PrivateRoute } from 'components/common/common';
import { AppRoute } from 'common/enums/enums';
import { Auth } from 'components/auth/auth';
import { Dashboard } from 'components/dashboard/dashboard';
```

2022-02-09 09:20 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +        />
```suggestion
        <PrivateRoute
          path={AppRoute.ROOT}
          element={<Dashboard />}
        />
```

2022-02-09 09:20 UTC, what1s1ove commented on frontend/src/components/common/private-route/private-route.tsx
> +  return children;
```suggestion
  return <>{children}</>;
```

2022-02-09 09:20 UTC, what1s1ove commented on frontend/src/hooks/hooks.ts
> +export { useLocation, useParams, useNavigate } from 'react-router-dom';
```suggestion
export { useLocation, useParams } from 'react-router-dom';
```
not sure that you use it

2022-02-09 09:20 UTC, what1s1ove commented on frontend/src/services/navigation/navigation.service.ts
> +export { Navigation };
```suggestion
import { AppRoute } from 'common/enums/enums';

type Constructor = {
  history: History;
};

class Navigation {
  #history: History;
  
  constructor({ history }: Constructor) {
    this.#history = history;
  }
  
  public push(path: AppRoute | string): void {
    this.#history.push(path);
  }
}

export { Navigation };
```

2022-02-09 09:20 UTC, what1s1ove commented on frontend/src/store/auth/reducer.ts
> +import { MasterDto } from 'bws-shared';
don't import directly from shared

2022-02-09 09:52 UTC, what1s1ove approved these changes

2022-02-09 09:53 UTC, merged