BWS-115: * fix bug with input value
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #121
Opened 2022-03-04 20:26 UTC by Oleg-feriss

2022-03-05 07:47 UTC, what1s1ove requested changes

2022-03-05 07:47 UTC, what1s1ove commented on frontend/src/components/eam-configurate-worker/eam-configurate-worker.tsx
> +    if (selectedGroups.selectedItems.length) {
```suggestion
    if (hasSelectedItems) {
```

2022-03-08 07:12 UTC, junojei commented on frontend/src/components/eam-configurate-worker/eam-configurate-worker.tsx
> +    const hasSelectedItems = selectedGroups.selectedItems.length;
```suggestion
    const hasSelectedItems = Boolean(selectedGroups.selectedItems.length);
```

2022-03-09 07:17 UTC, what1s1ove approved these changes

2022-03-09 07:17 UTC, merged