bws-95: * added backend functionality for update group
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #122
Opened 2022-03-05 12:38 UTC by bohdanshcherba

2022-03-06 06:37 UTC, what1s1ove commented on backend/src/api/eam/eam.api.ts
> +    method: HttpMethod.POST,
```suggestion
    method: HttpMethod.PUT,
```

2022-03-06 08:19 UTC, Yaroslaww-1 requested changes

2022-03-06 08:19 UTC, Yaroslaww-1 commented on backend/src/data/repositories/group/group.repository.ts
> +  }
Move these methods to GroupEntity:
```
in service:

const group = await repo.getGroupById()
group.addWorkersids();
await repo.save(group)
```

2022-03-09 07:24 UTC, what1s1ove requested changes

2022-03-09 07:24 UTC, what1s1ove commented on backend/src/api/eam/eam.api.ts
> +      const group = await groupService.update(req.query.id, req.body);
```suggestion
      const group = await groupService.update(req.params.id, req.body);
```

2022-03-09 07:24 UTC, what1s1ove commented on backend/src/api/eam/eam.api.ts
> +        Querystring: { id: string };
```suggestion
```
take it from params

2022-03-09 13:55 UTC, what1s1ove requested changes

2022-03-09 13:55 UTC, what1s1ove commented on backend/src/api/eam/eam.api.ts
> +        Params: { id: string };
create a separate type for it
check in other similar routes

2022-03-09 14:09 UTC, Yaroslaww-1 requested changes

2022-03-09 14:09 UTC, Yaroslaww-1 commented on backend/src/services/group/group.entity.ts
> +  }
Why do we need this checks? I think it's better to remove them.
If you want to validate input data it's always better to explicitly throw an exception

2022-03-16 18:29 UTC, bohdanshcherba commented
@Yaroslaww-1 can you close this branch without merge?

2022-03-18 14:58 UTC, closed without merging