BWS-127: add edit sc functionality (frontend)
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #128
Opened 2022-03-10 07:29 UTC by tbezrukava

<img width="1785" alt="Снимок экрана 2022-03-10 в 09 28 17" src="https://user-images.githubusercontent.com/95911156/157610684-79b4fbae-797b-495e-874d-2f62c9409eb6.png">
<img width="1785" alt="Снимок экрана 2022-03-10 в 09 28 59" src="https://user-images.githubusercontent.com/95911156/157610696-acbbb8e8-c3ab-4418-820e-279b850eabbc.png">

2022-03-10 08:19 UTC, Yaroslaww-1 requested changes

2022-03-10 08:19 UTC, Yaroslaww-1 commented on frontend/src/services/sc-api/sc-api.service.ts
> +  ): Promise<SCInstanceUpdateResponseDto> {
I'd rather split this param into two params:
```suggestion
  public async updateInstance(
    params: SCInstanceUpdateParamsDto,
    payload: SCInstanceUpdateRequestDto,
  ): Promise<SCInstanceUpdateResponseDto> {
```
It improves code readability imho

2022-03-10 10:03 UTC, tbezrukava commented
<img width="1785" alt="Снимок экрана 2022-03-10 в 12 00 55" src="https://user-images.githubusercontent.com/95911156/157638590-b6865a0b-8eb2-47e7-991a-9a26bd0f6bd9.png">

2022-03-11 09:18 UTC, what1s1ove commented on frontend/src/assets/img/edit-icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
```suggestion
<svg width="20" height="20" viewBox="0 0 20 20" fill="//add here our orange color" xmlns="http://www.w3.org/2000/svg">
```

2022-03-11 09:18 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +            path=":id"
```suggestion
            path="AppRoute.$ID"
```

2022-03-11 09:18 UTC, what1s1ove commented on frontend/src/components/common/button/button.tsx
> +  to?: AppRoute | string;
```suggestion
  to?: AppRoute;
```
cast a type where you need it (`anyString as AppRoute`)

2022-03-11 09:18 UTC, what1s1ove commented on frontend/src/components/common/icon-button/icon-button.tsx
> +  to?: AppRoute | string;
```suggestion
  to?: AppRoute;
```

2022-03-11 09:18 UTC, what1s1ove commented on frontend/src/components/sc-configurate-instance/components/update-instance-form/update-instance-form.tsx
> +import { navigation } from 'services/services';
```suggestion
```
you can't use services directly in the components. use react-dom hooks

2022-03-11 09:18 UTC, what1s1ove commented on frontend/src/components/sc/components/instances-table/components/action-cell/action-cell.tsx
> +        to={`${AppRoute.SC_CONFIGURATE_INSTANCE}/${id}`}
```suggestion
        to={`${AppRoute.SC_CONFIGURATE_INSTANCE}/${id}` as AppRoute}
```

2022-03-11 09:36 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-03-11 12:38 UTC, what1s1ove approved these changes

2022-03-11 12:39 UTC, merged