BWS31: + common component (button, input, checkbox, select)
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #13
Opened 2022-02-08 11:21 UTC by Zamay

2022-02-08 11:26 UTC, Zamay commented
![photo_2022-02-08 13 25 31](https://user-images.githubusercontent.com/17158157/152977963-b13f9fc7-06a1-49f4-bd38-aa4fa472a018.jpeg)

2022-02-08 11:43 UTC, tbezrukava commented on frontend/src/components/common/select/select.tsx
> +        //   singleValue: (provided) => ({ ...provided, color: '#fff' }),
creteria [B20](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md)

2022-02-08 11:43 UTC, tbezrukava commented on frontend/package.json
> +    "react-select": "^5.2.2"
```suggestion
    "react-select": "5.2.2"
```
creteria [B19](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md)

2022-02-08 12:36 UTC, what1s1ove requested changes

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
> +// import { Button } from 'components/common/common';
remove it

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/common/button/button.tsx
> +  color?: ButtonColor;
```suggestion
  btnStyle?: ButtonStyle;
```

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/common/enums/ui/button-color.enum.ts
> +  BLACK = 'black',
```suggestion
enum ButtonStyle {
  FILLED = 'filled',
  OUTLINED = 'outlined',
```

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/common/button/styles.module.scss
> +  cursor: pointer;
```suggestion
```
button has it as default

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/common/button/styles.module.scss
> +  height: 45px;
```suggestion
  min-height: 45px;
```

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/common/button/styles.module.scss
> +  background-color: #ff9c00;
add custom properties for colours `frontend/src/assets/css/variables.scss`

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/common/input/input.tsx
> +import clsx from 'clsx';
use `getValidClasses`

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/common/input/styles.module.scss
> +label {
don't use global styles

2022-02-08 12:36 UTC, what1s1ove commented on frontend/src/components/common/select/styles.module.scss
> +.react-select__container {
```suggestion
.reactSelectContainer {
```
use kebab case

2022-02-09 07:50 UTC, what1s1ove requested changes

2022-02-09 07:50 UTC, what1s1ove commented on .env.example/backend.env
> -SECRET_KEY={ENTER YOUR SECRET KEY HERE}
you delete a lot of think
left them. you should bring/change only change that you need in your task

2022-02-09 09:06 UTC, closed without merging