Task/bws16 master sign in
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #14
Opened 2022-02-08 12:44 UTC by Oleg-feriss

2022-02-08 12:49 UTC, what1s1ove requested changes

2022-02-08 12:49 UTC, what1s1ove commented on backend/src/common/enums/enums.ts
> +export * from './exception/exception';
avoid starts

2022-02-08 12:49 UTC, what1s1ove commented on backend/src/services/master/master.service.ts
> +  InvalidCredentialsErrorException,
```suggestion
```

2022-02-08 12:49 UTC, what1s1ove commented on backend/src/exceptions/invalid-credentials-error/invalid-credentials-error.exception.ts
> +class InvalidCredentialsErrorException extends Error {
we already have this error

2022-02-08 12:49 UTC, what1s1ove commented on backend/src/api/masters/masters.api.ts
> +      return rep.send(user).status(HttpCode.OK);
we also should return token

2022-02-08 14:32 UTC, Yaroslaww-1 requested changes

2022-02-08 14:32 UTC, Yaroslaww-1 commented on backend/src/api/masters/masters.api.ts
> +      return rep.send(user).status(HttpCode.OK);
Here should be MasterSignIn* instead of MasterSignUp* everywhere

2022-02-08 14:32 UTC, Yaroslaww-1 commented on backend/src/services/master/master.entity.ts
> +  public password: string;
Master entity cannot contain password directly. It should contain passwordHash, passwordSalt. Password hash cannot be decrypted

2022-02-08 14:32 UTC, Yaroslaww-1 commented on backend/src/services/master/master.service.ts
> +      user.password,
To verufy password you should do something like that: `hash(dto.password, user.salt) === user.passwordHash`

2022-02-08 14:32 UTC, Yaroslaww-1 commented on backend/src/services/master/master.service.ts
> +  }
Seems like this method is not used. Please remove it.

2022-02-08 14:32 UTC, Yaroslaww-1 commented on backend/src/services/master/master.service.ts
> +        ExceptionMessage.PASSWORDS_NOT_MATCH,
It's better to hide this information. You can show "invalid credentials" instead

2022-02-09 06:27 UTC, what1s1ove requested changes

2022-02-09 06:27 UTC, what1s1ove commented on backend/src/api/masters/masters.api.ts
> +      return rep.send(user).status(HttpCode.OK);
don't fixed

2022-02-09 06:27 UTC, what1s1ove commented on shared/src/common/types/master/master-sign-in-response-dto.type.ts
> +declare type MasterSignInResponseDto = {
```suggestion
import { MasterDto } from './master-dto.type';

type MasterSignInResponseDto = {
```

2022-02-09 06:27 UTC, what1s1ove commented on shared/src/common/types/master/master-sign-in-dto.type.ts
> +declare type MasterSignInDto = {
```suggestion
type MasterSignInDto = {
```

2022-02-09 06:27 UTC, what1s1ove commented on backend/src/api/masters/masters.api.ts
> +      return rep.send(user).status(HttpCode.OK);
```suggestion
      const signInUserPayload = await masterService.verifyLoginCredentials(req.body);
      return rep.send(signInUserPayload).status(HttpCode.OK);
```
do save for the sign-up request

2022-02-09 06:27 UTC, what1s1ove commented on backend/src/exceptions/invalid-credentials-error/invalid-credentials-error.ts
> -  } = {}) {
move it back

2022-02-09 06:27 UTC, what1s1ove commented on backend/src/services/master/master.service.ts
> +      )) === user.passwordHash;
encrypt has `compare` method

2022-02-09 08:30 UTC, Yaroslaww-1 requested changes

2022-02-09 08:30 UTC, Yaroslaww-1 commented on backend/src/api/masters/masters.api.ts
> +import { MasterSignUpRequestDto, MasterSignInDto } from '~/common/types/types';
MasterSignInRequestDto

2022-02-09 13:18 UTC, what1s1ove commented on backend/src/services/encrypt/encrypt.service.ts
> +  ): Promise<boolean> => (await this.createHash(data, salt)) === passwordHash;
```suggestion
  compare = async (
    data: string,
    salt: string,
    passwordHash: string,
  ): Promise<boolean> => {
  const hash = await this.createHash(data, salt)
  
  return hash === passwordHash;
  }
```

2022-02-09 13:31 UTC, Yaroslaww-1 submitted a review, later dismissed

2022-02-09 16:00 UTC, what1s1ove approved these changes

2022-02-09 16:00 UTC, merged