Task/bws131 add id and ip address to instance table
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #144
Opened 2022-03-14 15:58 UTC by tbezrukava

2022-03-14 16:04 UTC, tbezrukava commented
<img width="1565" alt="Снимок экрана 2022-03-14 в 18 04 34" src="https://user-images.githubusercontent.com/95911156/158212605-2c4f1162-0346-40c1-b304-bd069255ddc0.png">

2022-03-15 07:05 UTC, what1s1ove reviewed
remove `frontend/src/assets/img/icons8-key-2-20.png`

2022-03-15 07:05 UTC, what1s1ove commented on frontend/package.json
> +    "copy-to-clipboard": "3.3.1",
```suggestion
```
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

2022-03-15 07:05 UTC, what1s1ove commented on frontend/src/assets/img/key-icon.svg
> +<svg fill="none" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 50 50" width="20px" height="20px">
```suggestion
<svg fill="none" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 50 50" width="20" height="20">
```

2022-03-15 07:05 UTC, what1s1ove commented on frontend/src/components/sc/sc.tsx
> +  }, [sshKey, dispatch]);
```suggestion
```
do copy logic in the action after getting the key from server

2022-03-15 07:05 UTC, what1s1ove commented on frontend/src/store/sc/reducer.ts
> +  sshKey: SCSshKeyGetByIdResponseDto | null;
```suggestion
```
just copy in the clipboard in the action. you don't need it in the store

2022-03-16 08:41 UTC, what1s1ove requested changes

2022-03-16 08:41 UTC, what1s1ove commented on frontend/src/store/sc/reducer.ts
> +  sshKey: SCSshKeyGetByIdResponseDto | null;
isn't fixed

2022-03-16 08:53 UTC, merged