Task/bws 126 add run function functionality
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #145
Opened 2022-03-14 18:15 UTC by junojei

![localhost_3000_slc_configurate-function_a6fcf86d-a154-429c-a9bc-d8f1f7b616c3](https://user-images.githubusercontent.com/96128765/158235212-f6665541-a709-4076-81c4-e39a845378fd.png)
![localhost_3000_slc_configurate-function_a6fcf86d-a154-429c-a9bc-d8f1f7b616c3 (1)](https://user-images.githubusercontent.com/96128765/158235185-a144f9ce-c121-4a3e-ac86-7735e93958b4.png)

2022-03-15 06:59 UTC, what1s1ove requested changes

2022-03-15 06:59 UTC, what1s1ove commented on backend/src/services/aws/lambda/lambda.service.ts
> +    if (StatusCode !== 200 || !Payload) {
```suggestion
    if (StatusCode !== HttpCode.SUCCESS || !hasPayload) {
```

2022-03-15 06:59 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
> +// import { getResponse } from '..//../helpers/helpers';
```suggestion
```

2022-03-15 07:20 UTC, junojei commented
![localhost_3000_slc_configurate-function_533bbe87-f2f5-42ed-9eb8-f1bc95f9ce6a](https://user-images.githubusercontent.com/96128765/158326358-d4204866-50a4-4cd7-9e5c-16bd99a0bce3.png)

2022-03-15 20:23 UTC, junojei commented
![localhost_3000_slc_configurate-function_a6fcf86d-a154-429c-a9bc-d8f1f7b616c3 (2)](https://user-images.githubusercontent.com/96128765/158465371-288803be-01b2-49e5-b33b-1f2364d0a84c.png)

2022-03-16 08:48 UTC, what1s1ove requested changes

2022-03-16 08:48 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
> +            disabled={isPossibleSave ? false : true}
```suggestion
            disabled={!isPossibleSave}
```

2022-03-16 08:48 UTC, what1s1ove commented on frontend/package.json
> +    "underscore": "1.13.2"
remove this package and write a function by your self

2022-03-16 08:48 UTC, what1s1ove commented on frontend/package.json
> +    "@types/underscore": "1.11.4",
remove this package and write a function by your self

2022-03-16 08:48 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
> +import { debounce } from 'underscore';
```suggestion
```

2022-03-16 08:48 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
> +  const handleOnChangeValue = debounce(setEditCode, 500);
add constant for timeout

2022-03-16 09:17 UTC, Yaroslaww-1 requested changes

2022-03-16 09:17 UTC, Yaroslaww-1 commented on backend/src/common/enums/exception/exception-message.enum.ts
> +  FUNCTION_NOT_RUN: 'Function not run.',
```suggestion
  FUNCTION_NOT_RUN: 'An error occurred on function run .',
```

2022-03-16 09:17 UTC, Yaroslaww-1 commented on backend/src/services/aws/lambda/lambda.service.ts
> +    }
Two things here that are not quite correct me:
1. INTERNAL_SERVER_ERROR as a status. In 99% of cases there is no need to **explicitly** throw 500 error. 500 code is ok for an unhandled exceptions. But here you have explicitly defined catch
2. message is obscure. There are a lof of reasons for function to fail on run. Imagine you are using lambda service as a utility tool without knowing how it works internally. And than you receive FUNCTION_NOT_RUN exception. How would you debug it?)

Additionally, it seems like status code does not represent error. For example, everyone from [this thread](https://github.com/aws/aws-sdk-js-v3/issues/2007) use try/catch.
If you still want to provide more detailed exception you can use try/catch in s3.service createBucket method as an example

2022-03-17 06:22 UTC, what1s1ove requested changes

2022-03-17 06:22 UTC, what1s1ove commented on frontend/src/components/common/button/button.tsx
> +  disabled?: boolean;
```suggestion
  isDisabled?: boolean;
```

2022-03-17 06:22 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
> +  const TIMEOUT = 500;
*B16*

2022-03-17 06:22 UTC, what1s1ove commented on frontend/src/helpers/timeout/timeout.ts
> +const debounce = <A = unknown, R = void>(
move it to the shared folder

2022-03-18 07:53 UTC, what1s1ove requested changes

2022-03-18 07:53 UTC, what1s1ove commented on shared/src/helpers/timeout/timeout.ts
> +const debounce = <A = unknown, R = void>(
move to `shared/src/helpers/timeout/debounce.helper.ts` and then do reexport

2022-03-18 14:20 UTC, Yaroslaww-1 approved these changes

2022-03-18 15:42 UTC, what1s1ove approved these changes

2022-03-18 15:42 UTC, merged