BWS-118: + resetState actions
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #146
Opened 2022-03-14 19:10 UTC by tbezrukava

2022-03-14 19:14 UTC, Donymak approved these changes, later dismissed

2022-03-15 06:45 UTC, junojei approved these changes, later dismissed

2022-03-15 06:56 UTC, what1s1ove requested changes

2022-03-15 06:56 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +    dispatch(slcActions.resetState());
```suggestion
```
in any reducer you can add case for `authActions.logOut` it is easier than having shares for all scoops

2022-03-15 06:56 UTC, what1s1ove commented on frontend/src/store/bs/reducer.ts
> +import { deleteSpace, loadSpaces, resetState } from './actions';
```suggestion
import { logOut } from 'store/auth/actions';
 import { deleteSpace, loadSpaces } from './actions';
```

2022-03-15 06:56 UTC, what1s1ove commented on frontend/src/store/bs/reducer.ts
> +  builder.addCase(resetState, (state) => {
```suggestion
  builder.addCase(logOut, (state) => {
```

2022-03-15 14:23 UTC, junojei approved these changes

2022-03-16 08:35 UTC, what1s1ove approved these changes

2022-03-16 08:35 UTC, merged