Task/bws30 groups management
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #15
Opened 2022-02-08 15:39 UTC by Donymak

2022-02-08 18:29 UTC, Yaroslaww-1 requested changes

2022-02-08 18:29 UTC, Yaroslaww-1 commented on backend/src/common/types/group/group.ts
> +export { type GroupDto } from 'bws-shared/common/types/types';
GroupResponseDto

2022-02-08 18:29 UTC, Yaroslaww-1 commented on backend/src/services/group/group.entity.ts
> +    tenant_id,
tenantId

2022-02-09 06:23 UTC, what1s1ove requested changes

2022-02-09 06:23 UTC, what1s1ove commented on backend/src/data/repositories/group/group.repository.ts
> +  async getByName(name: string): Promise<GroupEntity | null> {
not sure that you use it

2022-02-09 06:23 UTC, what1s1ove commented on backend/src/services/group/group.entity.ts
> +    this.tenant_id = tenant_id;
```suggestion
    this.tenant_id = tenantId;
```

2022-02-09 06:23 UTC, what1s1ove commented on backend/src/services/group/group.entity.ts
> +      tenant_id,
```suggestion
      tenantId,
```

2022-02-09 06:23 UTC, what1s1ove commented on backend/src/services/group/group.service.ts
> +  async getAll(): Promise<GroupDto[]> {
not sure that we use it

2022-02-09 13:24 UTC, Yaroslaww-1 requested changes

2022-02-09 13:24 UTC, Yaroslaww-1 commented on backend/src/data/repositories/repositories.ts
> +const group = new Group({
groupRepository

2022-02-09 13:24 UTC, Yaroslaww-1 commented on backend/src/data/repositories/group/group.repository.ts
> +class Group {
GroupEntity

2022-02-11 16:07 UTC, closed without merging