Task/bws 105 permissions as list of chips
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #157
Opened 2022-03-18 15:37 UTC by junojei

1280x720
![localhost_3000_eam(1280x720) (1)](https://user-images.githubusercontent.com/96128765/159034076-eee263fa-f6bd-4a60-bd1e-64ec2ff533cb.png)
1920x1080
![localhost_3000_eam(1920x1080)](https://user-images.githubusercontent.com/96128765/159033959-8734129c-8edc-4180-bccc-1a9a73837cd8.png)
![localhost_3000_eam(1920x1080) (1)](https://user-images.githubusercontent.com/96128765/159033966-c095cd1f-97d7-4852-99e3-9f625c9cdf8b.png)

2022-03-18 18:40 UTC, what1s1ove requested changes

2022-03-18 18:40 UTC, what1s1ove commented on frontend/src/components/common/chip/chip.tsx
> +  return <button className={fullClassName}>{value}</button>;
```suggestion
  return <span className={fullClassName}>{value}</span>;
```
let's leave as span for now

2022-03-18 18:40 UTC, what1s1ove commented on frontend/src/components/common/chip/chip.tsx
> +  value: string;
```suggestion
```

2022-03-18 18:40 UTC, what1s1ove commented on frontend/src/components/common/chip/chip.tsx
> +  return <button className={fullClassName}>{value}</button>;
```suggestion
  return <button className={fullClassName}>{children}</button>;
```

2022-03-18 18:40 UTC, what1s1ove commented on frontend/src/components/common/chip/styles.module.scss
> +  cursor: pointer;
```suggestion
```

2022-03-18 18:40 UTC, what1s1ove commented on frontend/src/components/common/chip/chip.tsx
> +  chipStyle?: ChipStyle;
```suggestion
  chipStyle?: ChipStyle;
  chipColor??: ChipColor;
```
according to out design in figma

2022-03-19 08:32 UTC, Yaroslaww-1 approved these changes

2022-03-19 08:35 UTC, Yaroslaww-1 requested changes

2022-03-19 08:35 UTC, Yaroslaww-1 commented on frontend/src/components/common/chip/styles.module.scss
> +  padding: 10px;
I'd make vertical padding +-5px, and horizontal - 10px. Currently Chip component is too large in comparison to other table elements

2022-03-19 11:14 UTC, junojei commented
1280x720
default
![localhost_3000_eam(1280x720) (3)](https://user-images.githubusercontent.com/96128765/159118756-5cde26c7-04c0-466c-bd52-6937090fce7f.png)
possible styles
![localhost_3000_eam(1280x720) (4)](https://user-images.githubusercontent.com/96128765/159118757-b57cd4f7-d775-4c4b-b4b0-c14970bec69a.png)
![localhost_3000_eam(1280x720) (5)](https://user-images.githubusercontent.com/96128765/159118759-c6e93276-d237-45b7-ab3d-5235f1dd190f.png)
![localhost_3000_eam(1280x720) (6)](https://user-images.githubusercontent.com/96128765/159118760-6422c7c4-5855-4ae3-b9b5-f6106ffea658.png)

2022-03-19 11:34 UTC, junojei commented
fix icon size
![image](https://user-images.githubusercontent.com/96128765/159119464-78cbf897-5505-40ab-b0a9-eb6f345f15f3.png)
![localhost_3000_eam(1280x720) (10)](https://user-images.githubusercontent.com/96128765/159119489-a9186b04-6561-4f15-92f9-8023aaded79d.png)

2022-03-19 18:30 UTC, what1s1ove requested changes

2022-03-19 18:30 UTC, what1s1ove commented on frontend/src/common/enums/ui/icon-source.enum.ts
> +const IconSource = {
it isn't a enum. this is a map

move it to the `common/maps/ui/`

and name as 
```suggestion
const iconNameToSrc = {
```

2022-03-19 18:31 UTC, what1s1ove commented on frontend/src/common/enums/ui/icon-source.enum.ts
> +const IconSource = {
read more - https://binary-studio.com/2021/08/04/js-and-everyday-data-structures/

2022-03-20 06:26 UTC, ania-leichenko approved these changes

2022-03-20 07:48 UTC, what1s1ove approved these changes

2022-03-20 07:48 UTC, merged