Task/bws154 initial user data script while creating instance
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #163
Opened 2022-03-20 18:38 UTC by tbezrukava

<img width="1727" alt="Снимок экрана 2022-03-20 в 20 21 31" src="https://user-images.githubusercontent.com/95911156/159177376-8b6b7ac7-2b03-47ae-81ea-4288a62de22c.png">
<img width="870" alt="Снимок экрана 2022-03-20 в 20 22 29" src="https://user-images.githubusercontent.com/95911156/159177380-57799358-353b-474e-ac18-1312e96a8b1b.png">

2022-03-20 18:46 UTC, what1s1ove requested changes

2022-03-20 18:46 UTC, what1s1ove commented on frontend/src/components/common/input/input.tsx
>        <input
```suggestion
  return
    <label className={styles.inputLabel}>
      <span className={styles.span}>{label}</span>
       isTextarea ? (
    <textarea
      {...field}
      rows={rows}
      placeholder={placeholder}
      className={styles.textarea}
    />
  ) : ( <input
```

2022-03-20 18:46 UTC, what1s1ove commented on frontend/src/components/common/input/input.tsx
> +      className={styles.textarea}
we should have the same class for both inputs

2022-03-20 19:23 UTC, tbezrukava commented
<img width="1783" alt="Снимок экрана 2022-03-20 в 21 22 15" src="https://user-images.githubusercontent.com/95911156/159179146-85f3a338-a05e-4daf-90e2-a89c4aa59fa1.png">

2022-03-21 07:47 UTC, what1s1ove requested changes

2022-03-21 07:47 UTC, what1s1ove commented on frontend/src/components/common/input/input.tsx
> +          className={`${styles.input} ${styles.textarea}`}
use getValidClasses
we also need to handle an error on the text-aria

2022-03-21 09:18 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-03-21 10:02 UTC, Donymak submitted a review, later dismissed

2022-03-21 10:08 UTC, junojei commented on frontend/src/components/sc-configurate-instance/components/create-instance-form/create-instance-form.tsx
> +              rows={10}
A11?

2022-03-21 12:12 UTC, what1s1ove commented on frontend/src/components/sc-configurate-instance/components/create-instance-form/create-instance-form.tsx
> +              rows={10}
it's okay for now

2022-03-21 13:30 UTC, ania-leichenko approved these changes

2022-03-21 15:02 UTC, junojei approved these changes

2022-03-22 07:11 UTC, what1s1ove approved these changes

2022-03-22 07:11 UTC, merged