Task/bws 143 resize column functionality to table
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #164
Opened 2022-03-20 18:45 UTC by junojei

1920x1080
![localhost_3000_slc(1920x1080)](https://user-images.githubusercontent.com/96128765/159177587-985e80eb-82b5-4800-9256-b93024ab7cab.png)
1280x720
![localhost_3000_slc(1280x720) (2)](https://user-images.githubusercontent.com/96128765/159177599-6afeb450-a8c5-4419-b7e5-62ff2e3ac41c.png)
![localhost_3000_slc(1280x720) (3)](https://user-images.githubusercontent.com/96128765/159177603-9c264a34-dd74-4d9e-9819-2b523b3c8fd1.png)
![localhost_3000_slc(1280x720) (4)](https://user-images.githubusercontent.com/96128765/159177604-7be489ff-2d5f-40ab-938c-0319fd959a27.png)
![localhost_3000_slc(1280x720) (5)](https://user-images.githubusercontent.com/96128765/159177605-85bda38e-a6c1-407f-816a-798943d051e4.png)
![localhost_3000_slc(1280x720) (6)](https://user-images.githubusercontent.com/96128765/159177607-dd4a5bb5-e5ac-4ab0-b992-7ce00e1ffe67.png)

2022-03-20 18:49 UTC, junojei commented on frontend/src/assets/img/resize.svg
> +<!--! Font Awesome Pro 6.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
delete this?

2022-03-21 07:49 UTC, what1s1ove requested changes

2022-03-21 07:49 UTC, what1s1ove commented on frontend/.eslintrc.yml
> +ignorePatterns: [table-config.d.ts]
```suggestion
disable directly in the file
```

2022-03-21 07:49 UTC, what1s1ove commented on frontend/src/assets/img/resize.svg
> +<!--! Font Awesome Pro 6.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
if we don't need it

2022-03-21 08:40 UTC, Yaroslaww-1 submitted a review, later dismissed

2022-03-21 10:05 UTC, Donymak approved these changes, later dismissed

2022-03-21 13:30 UTC, ania-leichenko submitted a review, later dismissed

2022-03-22 07:12 UTC, what1s1ove approved these changes

2022-03-22 07:12 UTC, merged