BWS-81: * fix bugs
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #165
Opened 2022-03-21 08:15 UTC by Oleg-feriss

2022-03-21 08:39 UTC, Yaroslaww-1 requested changes

2022-03-21 08:39 UTC, Yaroslaww-1 commented on backend/src/services/worker/worker.service.ts
> +        return this.#slcFunctionService.delete({ id });
I don't like this solution, honestly. It is not obvious why token in SlcFunctionService.delete can be null. You have 2 possible options:
1. Do not use slcFunctionService.delete and spaceService.delete. And just copy code from these methods into WorkerService.deleteWorker. (can't recommend this approach)
2. Move role checks to the api layer (as with permissions check)

2022-03-22 07:20 UTC, what1s1ove requested changes

2022-03-22 07:20 UTC, what1s1ove commented on backend/src/api/slc/slc.api.ts
> +
```suggestion
```
we can't do it here

2022-03-22 07:20 UTC, what1s1ove commented on backend/src/api/bs/bs.api.ts
> +      }
```suggestion
```
we can't do it here

2022-03-22 08:30 UTC, Yaroslaww-1 commented on backend/src/api/bs/bs.api.ts
> +      }
We can actually

2022-03-22 08:39 UTC, Yaroslaww-1 requested changes

2022-03-22 08:39 UTC, Yaroslaww-1 commented on backend/src/services/worker/worker.service.ts
>      }
Move it to api layer as you done with slc/bs delete methods

2022-03-25 11:37 UTC, what1s1ove approved these changes

2022-03-25 11:38 UTC, Yaroslaww-1 approved these changes

2022-03-25 11:38 UTC, merged