Task/bws156 output os for table
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #166
Opened 2022-03-21 11:49 UTC by tbezrukava

<img width="1783" alt="Снимок экрана 2022-03-21 в 13 21 16" src="https://user-images.githubusercontent.com/95911156/159251777-fe184f2e-aec7-405a-bdf1-7e8e7897c415.png">

2022-03-21 12:11 UTC, what1s1ove submitted a review, later dismissed

2022-03-21 12:35 UTC, Yaroslaww-1 requested changes

2022-03-21 12:35 UTC, Yaroslaww-1 commented on backend/src/data/repositories/instance/instance.repository.ts
> +  ): Promise<InstanceM> {
```suggestion
  ): Promise<InstanceEntity> {
```

2022-03-21 12:35 UTC, Yaroslaww-1 commented on backend/src/data/repositories/instance/instance.repository.ts
>      },
Ideally method should look like that:
```
public async updateById(instance: InstanceEntity): Promise<void>
```

2022-03-21 12:35 UTC, Yaroslaww-1 commented on backend/src/data/repositories/instance/instance.repository.ts
> +  }): Promise<InstanceM[]> {
```suggestion
  }): Promise<InstanceEntity[]> {
```
You can add operationSystem property yo your entity

2022-03-22 06:17 UTC, ania-leichenko approved these changes, later dismissed

2022-03-22 07:18 UTC, what1s1ove requested changes

2022-03-22 07:18 UTC, what1s1ove commented on backend/src/services/operation-system/operation-system.service.ts
> +import { SCError } from '~/exceptions/sc-error/sc-error';
```suggestion
import { SCError } from '~/exceptions/exceptions';
```

2022-03-22 08:05 UTC, what1s1ove approved these changes, later dismissed

2022-03-22 08:28 UTC, Yaroslaww-1 requested changes

2022-03-22 08:28 UTC, Yaroslaww-1 commented on backend/src/services/instance/instance.entity.ts
> +  public operationSystem: SCInstanceRelatedItem;
Dto is used **only** for sharing API responses types with frontend. You should never use dto for any other types. If you need backend specific enums/types you must create them on backend only. You can either use src/common/enums folder or src/services/instance

2022-03-22 12:28 UTC, junojei commented on frontend/src/components/sc/components/instances-table/helpers/get-columns.helper.ts
> +      accessor: InstancesTableAccessor.OS,
```suggestion
      Header: InstancesTableHeader.OS,
      accessor: InstancesTableAccessor.OS,
      minWidth: 100,
      width: 200,
```

2022-03-22 12:30 UTC, junojei commented on frontend/src/components/sc/components/instances-table/helpers/get-columns.helper.ts
> +      accessor: InstancesTableAccessor.OS,
Now we have resizable column.

2022-03-22 13:45 UTC, junojei approved these changes

2022-03-22 17:49 UTC, what1s1ove approved these changes

2022-03-22 18:48 UTC, Yaroslaww-1 approved these changes

2022-03-22 18:52 UTC, merged