Task/bws71 pagination for worker table
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #167
Opened 2022-03-21 11:54 UTC by ania-leichenko

![Screenshot_82](https://user-images.githubusercontent.com/65825815/159255875-54027db2-e793-4aed-b83d-17f2361a6f92.png)

2022-03-21 12:10 UTC, Donymak commented on frontend/src/components/eam/eam.tsx
> +  };
change forward to previous or prev
(Forward means the same as Next)

2022-03-21 12:25 UTC, Donymak commented on backend/src/data/repositories/worker/worker.repository.ts
> +    return countItems;
```suggestion
    return workers.length;
```

2022-03-21 12:29 UTC, Donymak commented
delete empty file:
frontend/src/assets/img/arrow.svg

2022-03-21 16:27 UTC, YaroslavAntoniuk requested changes

2022-03-21 16:27 UTC, YaroslavAntoniuk commented on backend/src/services/worker/worker.service.ts
> +    return { items: workers, countItems: countItems };
return { items: workers, countItems };

2022-03-21 16:27 UTC, YaroslavAntoniuk commented on frontend/src/components/eam/eam.tsx
> +  const allPage = Math.ceil(countItems / 5);
Move this magic number(5) to constant

2022-03-21 16:27 UTC, YaroslavAntoniuk commented on frontend/src/components/eam/eam.tsx
> +      );
This code used twice in this file, could we just move it into different function like `handleLoadWorkers(tenantId, from, count)`

2022-03-21 19:54 UTC, Yaroslaww-1 requested changes

2022-03-21 19:54 UTC, Yaroslaww-1 commented on frontend/src/components/eam/eam.tsx
> +        >
Pagination should be generic. Something like that:
```
<WorkersTable 
   withPagination
   fetchPage={({ page, pageSize }) => ...}
/>
```

2022-03-22 07:17 UTC, what1s1ove requested changes

2022-03-22 07:17 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +    return workers.length;
you need to get count from the DB

2022-03-22 07:17 UTC, what1s1ove commented on frontend/src/common/constants/workers.constants.ts
> +const WORKERS_PER_PAGE = 5;
*B17*

2022-03-22 07:17 UTC, what1s1ove commented on frontend/src/common/constants/workers.constants.ts
> +const WORKER_BACK_PAGE = 5;
it isn't only for the workers

2022-03-22 07:17 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +  footer?: React.ReactNode;
```suggestion
```

2022-03-22 07:17 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +      {footer}
```suggestion
// add markup for pagination here
```

2022-03-22 07:17 UTC, what1s1ove commented on frontend/src/components/eam/components/workers-table/workers-table.tsx
> +};
```suggestion
```

2022-03-22 07:17 UTC, what1s1ove commented on frontend/src/components/eam/eam.tsx
> +  const handleBackPage = (): void => {
since we will use pagination for a lot of pages, we need to create a custom hook for it

2022-03-22 07:17 UTC, what1s1ove commented on frontend/src/components/eam/eam.tsx
> +          }
```suggestion
```
pagination should be in the common table, but props should be optional
and if we have all props that we need for pagination, we should render the pagination itself

2022-03-22 11:48 UTC, junojei commented on frontend/src/common/constants/workers.constants.ts
> +const WORKER_CURRENT_PAGE = 1;
`const WORKER_CURRENT_PAGE = 1;`
I think it's not a const, its state of the current table.

2022-03-22 11:48 UTC, junojei commented on frontend/src/components/eam/eam.tsx
> +  );
I think its not necessarily.
```suggestion
  const { tenantId, countItems: countItems } = useAppSelector(
    ({ app, eam }) => ({
      tenantId: app.tenant?.id,
      countItems: eam.countItems,
    }),
  );
```

2022-03-22 14:38 UTC, ania-leichenko commented on frontend/src/components/eam/eam.tsx
> +  );
This is not from my pull request and assignment, not sure if it needs to be edited here

2022-03-22 17:14 UTC, junojei commented on frontend/src/components/eam/eam.tsx
> +  );
Here added id property what immediately overwritten in tenantId, I think we don't need it.
Wait what the coaches say.

2022-03-22 17:16 UTC, junojei commented on frontend/src/components/eam/eam.tsx
> +  );
```suggestion
  const { id: tenantId, countItems } = useAppSelector(
    ({ app, eam }) => ({
      id: app.tenant?.id,
      countItems: eam.countItems,
    }),
  );
```

2022-03-23 07:49 UTC, what1s1ove requested changes

2022-03-23 07:49 UTC, what1s1ove commented on frontend/src/components/pagination/pagination.tsx
> +  };
```suggestion
```
we will reuse this functionality
all this data should come from props

2022-03-23 07:49 UTC, what1s1ove commented on frontend/src/components/eam/styles.module.scss
> +.pagination {
not sure that we need it here

2022-03-23 07:49 UTC, what1s1ove commented on frontend/src/common/enums/worker/workers.enum.ts
> +enum Page {
```suggestion
enum Pagination {
```
not sure about the name. since we will use it not only for worker, you need to more into other folder

2022-03-23 07:49 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +      <Pagination />
```suggestion
     const hasPagination = // all things that we need for the pagination
      {hasPagination && <Pagination />}
```

2022-03-23 07:49 UTC, what1s1ove commented on frontend/src/components/pagination/pagination.tsx
> +  };
we need to create a custom hook for reuse pagination for other pages

2022-03-23 07:49 UTC, what1s1ove commented on frontend/src/components/pagination/pagination.tsx
> +        <div className={styles.count}>{countItems + 'results'}</div>
```suggestion
        <div className={styles.count}>{countItems} results</div>
```

2022-03-24 13:44 UTC, what1s1ove requested changes

2022-03-24 13:44 UTC, what1s1ove commented on frontend/src/common/enums/pagination/pagination.enum.ts
> +enum PaginationEnum {
```suggestion
enum Pagination {
```

2022-03-24 13:44 UTC, what1s1ove commented on frontend/src/common/types/app/use-pagination-hook.type.ts
> +} | null;
```suggestion
};
```

2022-03-24 13:44 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +    handleLoad: (from: number) => void;
*A8*

2022-03-24 13:44 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +  const paginationProps = usePagination(pagination);
we should call usePagination in only it tables, where we need it. not inside in the common table

2022-03-24 13:44 UTC, what1s1ove commented on frontend/src/components/eam/components/workers-table/workers-table.tsx
> +}> = ({ children }) => {
```suggestion
const WorkersTable: FC<Props> = ({ children }) => {
```

2022-03-24 13:44 UTC, what1s1ove commented on frontend/src/hooks/use-pagination/use-pagination.hook.ts
> +  const [currentPage, setCurrentPage] = useState(1);
```suggestion
  pagination: UsePaginationArgs,
): UsePaginationtemsHook => {

  const [from, setFrom] = useState(0 // initial value should come from props);
  const [currentPage, setCurrentPage] = useState(1 // initial value should come from props);
```

2022-03-24 13:44 UTC, what1s1ove commented on frontend/src/components/eam/components/workers-table/workers-table.tsx
> +        count: 5,
add constant

2022-03-26 05:56 UTC, what1s1ove requested changes

2022-03-26 05:56 UTC, what1s1ove commented on frontend/src/common/enums/enums.ts
> +export { Pagination } from './pagination/pagination.enum';
```suggestion
export { Pagination } from './pagination/pagination';
```

2022-03-26 05:56 UTC, what1s1ove commented on frontend/src/hooks/use-pagination/use-pagination.hook.ts
> +  from?: number;
```suggestion
  from: number;
```

2022-03-26 05:56 UTC, what1s1ove commented on frontend/src/hooks/use-pagination/use-pagination.hook.ts
> +  perPage: number;
```suggestion
  perPageCount: number;
```

2022-03-26 05:56 UTC, what1s1ove commented on frontend/src/components/pagination/pagination.tsx
> +  handleNextPage?: () => void;
**A8**

2022-03-26 05:56 UTC, what1s1ove commented on frontend/src/components/eam/components/workers-table/workers-table.tsx
> +        count: Pagination.PER_PAGE,
should come from arguments

2022-03-26 05:56 UTC, what1s1ove commented on frontend/src/components/common/table/table.tsx
> +    handleNextPage: () => void;
*A8*

2022-03-26 05:56 UTC, what1s1ove commented on frontend/src/hooks/use-pagination/use-pagination.hook.ts
> +  const [currentPage, setCurrentPage] = useState(pagination.currentPage ?? 1);
```suggestion
  const [from, setFrom] = useState(pagination.from ?? INITIAL_FROM_COUNT);
  const [currentPage, setCurrentPage] = useState(pagination.currentPage ?? INITIAL_CURRENT_PAGE);
```

2022-03-26 11:12 UTC, what1s1ove approved these changes

2022-03-26 11:12 UTC, merged