Task/bws163 get objects endpoint
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #178
Opened 2022-03-23 13:06 UTC by Donymak

![image](https://user-images.githubusercontent.com/86227025/159706025-b8dc33ba-6e90-44df-9fbd-0d6d7c559027.png)

2022-03-23 15:22 UTC, what1s1ove requested changes
👍

2022-03-23 15:22 UTC, what1s1ove commented on backend/src/common/types/types.ts
> +export { type UploadPayload } from 'src/common/types/bs-object/bs-object-upload-payload.type';
move it back

2022-03-23 15:42 UTC, Donymak commented on backend/src/common/types/types.ts
> +export { type UploadPayload } from 'src/common/types/bs-object/bs-object-upload-payload.type';
Where?)
Upload payload was in file `'src/common/types/bs-object/bs-object'`
As in other folders with types, a file with the name of an entity(space, worker, etc.) of the exact folder contains reexports from the built shared package. File with name bs-object is used as in other folders, code style is OK(I guess)

Here I see only a typo on 96'st string)

2022-03-24 08:03 UTC, Yaroslaww-1 submitted a review, later dismissed

2022-03-24 11:44 UTC, ania-leichenko submitted a review, later dismissed

2022-03-26 08:34 UTC, junojei commented on backend/src/api/bs/bs.api.ts
> +      return rep.send(spaces).status(HttpCode.OK);
maybe better name objects or spaceObjects?
```suggestion
      const objects = await bsObjectService.getObjects({
        spaceId: req.params.id,
        from: req.query.from,
        count: req.query.count,
        token,
      });

      return rep.send(objects).status(HttpCode.OK);
```

2022-03-26 09:09 UTC, junojei commented on backend/src/common/types/types.ts
> +} from '~/common/types/bs-object/bs-object';
```suggestion
} from './bs-object/bs-object';
```

2022-03-26 09:20 UTC, what1s1ove approved these changes

2022-03-26 09:20 UTC, what1s1ove commented on backend/src/common/types/types.ts
> +export { type UploadPayload } from 'src/common/types/bs-object/bs-object-upload-payload.type';
<img width="582" alt="image" src="https://user-images.githubusercontent.com/42296182/159764462-c3fc5f25-c12d-46ba-8203-7a4b2b55804d.png">

2022-03-26 09:20 UTC, merged