bws-166: + added list of permission
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #180
Opened 2022-03-23 20:37 UTC by bohdanshcherba

2022-03-24 07:26 UTC, what1s1ove requested changes
you just need to add `Chip` component on permissions
why are there so many changes?

2022-03-24 07:50 UTC, Yaroslaww-1 requested changes

2022-03-24 07:50 UTC, Yaroslaww-1 commented on frontend/src/components/eam-configurate-worker/components/group-table/group-table.tsx
> +import React, { FC } from 'react';
Please add screenshot of groups table

2022-03-24 08:40 UTC, bohdanshcherba commented
![image](https://user-images.githubusercontent.com/73034554/159876429-9d4bcf64-9ef4-4a07-9e43-dd7a3fe3751f.png)

2022-03-24 09:53 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-03-24 11:43 UTC, ania-leichenko approved these changes, later dismissed

2022-03-24 13:37 UTC, what1s1ove requested changes
in this PR we just need to add a `Chip` component to permissions table. without any other changes

2022-03-24 17:32 UTC, junojei commented on frontend/src/components/eam-configurate-worker/components/group-table/group-table.tsx
> +import React, { FC } from 'react';
```suggestion
import { FC } from 'react';
```

2022-03-25 15:26 UTC, what1s1ove requested changes
in this PR we just need to add a `Chip` component to permissions table. without any other changes
we should have only 1-2 file changed. Now we have 17

2022-03-25 18:49 UTC, closed without merging