bws-150: * added loader to the table
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #196
Opened 2022-03-25 14:28 UTC by bohdanshcherba

2022-03-25 15:24 UTC, what1s1ove requested changes

2022-03-25 15:24 UTC, what1s1ove commented on frontend/src/components/bs/components/spaces-table/spaces-table.tsx
> +import { DataStatus } from '../../../../common/enums/app/data-status.enum';
```suggestion
import { DataStatus } from 'common/enums/enums';
```
fix for all

2022-03-25 15:24 UTC, what1s1ove commented on frontend/src/components/common/table/styles.module.scss
> +  height: 300px;
```suggestion
  min-height: 300px;
```

2022-03-25 22:11 UTC, ania-leichenko approved these changes

2022-03-26 05:47 UTC, what1s1ove approved these changes

2022-03-26 05:47 UTC, merged