Task/bws17 add master signup
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #2
Opened 2022-02-06 07:24 UTC by tbezrukava

2022-02-06 09:00 UTC, Yaroslaww-1 requested changes

2022-02-06 09:00 UTC, Yaroslaww-1 commented on backend/src/api/masters/masters.api.ts
> +      }
We definitely don't want to write try/catch in every route. I don't know exactly what issue is but if you want to handle unhandled exceptions look at global error hadling in fastify - https://www.fastify.io/docs/latest/Reference/Server/#seterrorhandler

2022-02-06 09:00 UTC, Yaroslaww-1 commented on backend/src/services/master/master.service.ts
> +  async login(id: string): Promise<MasterPromise> {
Services should return Dtos that specified in [(bws shared folder/](https://github.com/BinaryStudioAcademy/bsa-winter-2021-2022-bws/blob/development/shared/src/common/types/types.ts)

2022-02-06 09:00 UTC, Yaroslaww-1 commented on backend/src/data/repositories/master/master.repository.ts
> +      passwordHash: await encrypt(password, salt),
Repository should not contain any logic except database querying/inserting. Entity you pass to repository should contain all required info

2022-02-06 09:42 UTC, what1s1ove requested changes

2022-02-06 09:42 UTC, what1s1ove commented on backend/package.json
> +    "@types/jsonwebtoken": "^8.5.8",
types should be in the `dev` dependencies

2022-02-06 09:42 UTC, what1s1ove commented on backend/package.json
> +    "@types/bcrypt": "^5.0.0",
all packages' version should be fixed

2022-02-06 09:42 UTC, what1s1ove commented on shared/src/exceptions/invalid-credentials-error/invalid-credentials-error.ts
> +class InvalidCredentialsError extends Error {
in the shared folder, we need only shared thing
since we will use it only on the backend, move it there

2022-02-06 09:42 UTC, what1s1ove commented on backend/src/helpers/crypt/encrypt/encrypt.helper.ts
> +import { hash, genSaltSync } from 'bcrypt';
let's create a service `encrypt`

2022-02-06 09:42 UTC, what1s1ove commented on backend/src/services/master/master.service.ts
> +    const masterByName = await this.#masterRepository.getByFilter('name', name);
users can have the save name
so we don't need this check

2022-02-06 09:42 UTC, what1s1ove commented on backend/src/data/repositories/master/master.repository.ts
> +    filterName: Filter,
since we need need get use by name, we should have two separate methods
`getMasterById` and `getMasterByEmail`

2022-02-07 06:07 UTC, what1s1ove requested changes

2022-02-07 06:07 UTC, what1s1ove commented on shared/src/common/types/master/master-sign-up-response-dto.type.ts
> +type MasterSignUpResponseDto = MasterDto & { token: string };
```suggestion
type MasterSignUpResponseDto = {
  user: MasterDto
  token: string
}
```

2022-02-07 06:07 UTC, what1s1ove commented on backend/src/services/encrypt/encrypt.service.ts
> +    this.saltRounds = rounds || saltRounds;
```suggestion
    this.saltRounds = rounds ?? MASTER_PASSWORD_SALT_ROUNDS;
```

2022-02-07 06:07 UTC, what1s1ove commented on backend/src/helpers/token/create-token/create-token.helper.ts
> +const createToken = (data: string): string =>
we also need service for token. in the future we will have `verify` and other methods

2022-02-07 06:07 UTC, what1s1ove commented on backend/src/services/master/master.service.ts
> +import { InvalidCredentialsError } from '~/exceptions/invalid-credentials-error/invalid-credentials-error';
```suggestion
import { InvalidCredentialsError } from '~/exceptions/exceptions';
```
always do reexport

2022-02-07 07:27 UTC, Yaroslaww-1 requested changes

2022-02-07 07:27 UTC, Yaroslaww-1 commented on backend/src/data/repositories/master/master.repository.ts
> +  async create(master: MasterCreate): Promise<MasterM> {
You should user `master: MasterEntity` here. No need to create another type

2022-02-07 09:21 UTC, what1s1ove requested changes

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/data/repositories/master/master.repository.ts
> +  async getByEmail(email: string): Promise<MasterEntity | undefined> {
```suggestion
  async getByEmail(email: string): Promise<MasterEntity | null> {
```

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/data/repositories/master/master.repository.ts
> +      return;
```suggestion
      return null;
```

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/data/repositories/master/master.repository.ts
> +  async getById(id: string): Promise<MasterEntity | undefined> {
```suggestion
  async getById(id: string): Promise<MasterEntity | null> {
```

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/data/repositories/master/master.repository.ts
> +    }
```suggestion

    if (!master) {
      return null;
    }
```

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/services/encrypt/encrypt.service.ts
> +  createSalt = (): string => genSaltSync(this.saltRounds);
```suggestion
  createSalt = (): string => genSalt(this.saltRounds);
```
prefer async

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/services/encrypt/encrypt.service.ts
> +    this.saltRounds = rounds ?? MASTER_PASSWORD_SALT_ROUNDS;
```suggestion
  #saltRounds: number;

  constructor(rounds?: number) {
    this.#saltRounds = rounds ?? MASTER_PASSWORD_SALT_ROUNDS;
```

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/services/master/master.service.ts
> +      token: createToken(id),
```suggestion
      token: this.#tokenService.createToken(id),
```

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/services/master/master.service.ts
> +import { encrypt } from '~/services/services';
```suggestion
```
services should be provided only through constructor

2022-02-07 09:21 UTC, what1s1ove commented on backend/src/services/master/master.service.ts
>    masterRepository: typeof masterRep;
```suggestion
  masterRepository: typeof masterRep;
  encryptService: typeof encryptServ
```

2022-02-07 11:44 UTC, what1s1ove commented on backend/src/services/services.ts
> +const encryptService = new Encrypt();
```suggestion
const token = new Token();
const encrypt = new Encrypt();
```

2022-02-07 11:44 UTC, what1s1ove commented on backend/src/services/services.ts
> +  encryptService,
```suggestion
  tokenService: token,
  encryptService: encrypt,
```

2022-02-07 12:00 UTC, what1s1ove approved these changes

2022-02-07 12:00 UTC, what1s1ove commented
LGTM 👍

2022-02-07 12:00 UTC, merged