Task/bws 185 pass arguments to the function custom popup
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #206
Opened 2022-03-26 15:08 UTC by junojei

1280x720

https://user-images.githubusercontent.com/96128765/160245601-17c1efb4-ef13-4395-ad50-a569fda54b80.mp4

2022-03-26 16:39 UTC, what1s1ove requested changes

2022-03-26 16:39 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/components/slc-popup/slc-popup.tsx
> +        ></Editor>
```suggestion
        />
```

2022-03-26 16:39 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/components/slc-popup/slc-popup.tsx
> +          ></Button>
```suggestion
          />
          <Button
            className={styles.button}
            btnStyle={ButtonStyle.FILLED}
            label="Run"
            onClick={handleOnRun}
          />
```

2022-03-26 16:39 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/styles.module.scss
> +  width: 100px;
why?
left `min-width`

2022-03-26 16:39 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
> +      )}
```suggestion
        <SLCPopup
          isOpen={isVisibleSLCPopup}
          onClose={handleCloseSLCPopup}
          onRun={handleRun}
        />
```

2022-03-26 17:43 UTC, junojei commented on frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
> +      )}
I do it for reset the component

2022-03-26 18:02 UTC, ania-leichenko approved these changes, later dismissed

2022-03-26 18:43 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-03-27 07:00 UTC, what1s1ove requested changes

2022-03-27 07:00 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/components/slc-popup/slc-popup.tsx
> +    onRun(value);
what if an error occurs? you need to handle it. check redux toolkit documentation

2022-03-27 07:00 UTC, what1s1ove commented on frontend/src/components/slc-configurate-function/components/edit-form/components/slc-popup/slc-popup.tsx
> +    onRun(value);
request after fix

2022-03-27 10:51 UTC, what1s1ove approved these changes

2022-03-27 10:51 UTC, merged