BWS-179: + apply-pagination-hook-for-all-tables
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #215
Opened 2022-03-27 20:00 UTC by ania-leichenko

![Screenshot_1](https://user-images.githubusercontent.com/65825815/160298583-0a90a4f6-855c-4a2a-afe6-5cd540e3de0e.png)
![Screenshot_2](https://user-images.githubusercontent.com/65825815/160298587-2150e421-a324-4ac5-9b3b-2d45de40d75c.png)
![Screenshot_3](https://user-images.githubusercontent.com/65825815/160298593-40b1aa65-6469-4e1e-b8a3-3baa28e589fd.png)
![Screenshot_4](https://user-images.githubusercontent.com/65825815/160298607-307ed8aa-528f-4b6d-ab4b-fb5ea2e3a307.png)
![Screenshot_5](https://user-images.githubusercontent.com/65825815/160298614-b1ec5811-b496-412c-90b7-bb351268942e.png)

2022-03-27 20:56 UTC, Donymak commented on frontend/src/components/bs/components/spaces-table/spaces-table.tsx
> +import { Pagination } from 'common/enums/enums';
```suggestion
import { DataStatus, Pagination  } from 'common/enums/enums';
```
in every service table component

2022-03-28 04:44 UTC, what1s1ove requested changes

2022-03-28 04:44 UTC, what1s1ove commented on backend/src/data/repositories/slc-function/slc-function.repository.ts
> +    return await this.#SLCFunctionModel
```suggestion
  public getCount(filter: SLCFunctionGetFilter): Promise<number> {
    const { tenantId } = filter;

    return this.#SLCFunctionModel
```

2022-03-28 04:44 UTC, what1s1ove commented on backend/src/data/repositories/group/group.repository.ts
> +  public async getCount(
```suggestion
  public getCount(
```

2022-03-28 04:44 UTC, what1s1ove commented on backend/src/data/repositories/instance/instance.repository.ts
> +  public async getCount(tenantId: string): Promise<number> {
```suggestion
  public getCount(tenantId: string): Promise<number> {
```

2022-03-28 04:44 UTC, what1s1ove commented on frontend/src/components/bs/components/spaces-table/spaces-table.tsx
> +import { Pagination } from 'common/enums/enums';
agreed

2022-03-28 06:30 UTC, what1s1ove approved these changes

2022-03-28 06:31 UTC, merged