Fix/bws202 error is shown after opening configurate group
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #222
Opened 2022-03-28 17:32 UTC by tbezrukava

2022-03-28 18:34 UTC, what1s1ove requested changes

2022-03-28 18:34 UTC, what1s1ove commented on backend/src/api/eam/eam.api.ts
> +    url: `${EAMApiPath.GROUP}${GroupsApiPath.$ID}`,
actually we want to have only `groups`. please, remove `group` from enum at all

2022-03-28 21:33 UTC, Yaroslaww-1 approved these changes

2022-03-29 01:16 UTC, what1s1ove approved these changes
👍

2022-03-29 01:16 UTC, merged