BWS-215: + change-titles-on-the-edit-create-group-pages
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #231
Opened 2022-03-29 14:50 UTC by ania-leichenko

![Screenshot_1](https://user-images.githubusercontent.com/65825815/160639134-d3b273dc-eab5-44d2-b7d2-6e46cfda350e.png)
![Screenshot_2](https://user-images.githubusercontent.com/65825815/160639152-b1e871eb-cc1a-40cc-a82f-54e7041f2f86.png)
![Screenshot_3](https://user-images.githubusercontent.com/65825815/160639172-7ff3aa59-78a6-499a-90b1-4d73928aff17.png)
![Screenshot_4](https://user-images.githubusercontent.com/65825815/160639186-8cb5ec75-ad7e-4fd6-a8d3-c7af332a8c8c.png)

2022-03-29 14:51 UTC, what1s1ove requested changes

2022-03-29 14:51 UTC, what1s1ove commented on frontend/src/components/eam-configurate-group/components/permissions-table/permissions-table.tsx
> +        {hasGroup ? 'Edit permissions policies' : 'Attach permissions policies'}
```suggestion
        {hasGroup ? 'Edit' : 'Attach'} permissions policies
```

2022-03-29 14:51 UTC, what1s1ove commented on frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
> +                {hasGroup ? 'Edit group name' : 'Name the group'}
same

2022-03-29 14:51 UTC, what1s1ove commented on frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
> +          {hasGroup ? 'Edit Group' : 'Create group'}
case?
same

2022-03-29 15:54 UTC, Yaroslaww-1 approved these changes

2022-03-29 19:38 UTC, junojei approved these changes

2022-03-30 06:49 UTC, what1s1ove approved these changes

2022-03-30 06:49 UTC, merged