Task/bws47 add app header
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #24
Opened 2022-02-10 09:00 UTC by junojei

1920x1080
![зображення](https://user-images.githubusercontent.com/96128765/153372296-7be33708-fc9f-47b3-957b-edd59c1d6385.png)
![зображення](https://user-images.githubusercontent.com/96128765/153372390-61bb91ae-93ab-4eec-af2b-287ef2fbf564.png)
1920x1080 with background
![зображення](https://user-images.githubusercontent.com/96128765/153372679-c74de009-d8ac-4eff-a5e4-f27612ba347b.png)
1280x720 with background
![зображення](https://user-images.githubusercontent.com/96128765/153372835-705412d6-2300-4e0b-be1b-39ccb844757e.png)

2022-02-10 09:10 UTC, what1s1ove requested changes

2022-02-10 09:10 UTC, what1s1ove commented on frontend/src/components/dashboard/header/header.tsx
> +import logo from 'assets/img/logo.svg';
header is a common component

2022-02-10 09:10 UTC, what1s1ove commented on frontend/src/components/dashboard/header/header.tsx
> +          <div className={styles.profile}>
we need to fetch tenant to output the info here

2022-02-10 09:10 UTC, what1s1ove commented on frontend/src/components/dashboard/header/header.module.scss
> +.dropdownMenu img {
don't use tag selector

2022-02-10 14:42 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-02-11 07:09 UTC, junojei reviewed
1920x1280
![зображення](https://user-images.githubusercontent.com/96128765/153550444-d02e0e16-8bde-4a11-9745-e17f4f3781aa.png)
1280x720
![зображення](https://user-images.githubusercontent.com/96128765/153550519-e99101c9-cfc6-4de5-a7e4-33b717de9990.png)

2022-02-11 07:25 UTC, what1s1ove requested changes

2022-02-11 07:25 UTC, what1s1ove commented on frontend/src/components/dashboard/dashboard.tsx
> +      {tenantStatus === 'fulfilled' ? (
```suggestion
      {tenantStatus === 'fulfilled' ? (
```
use data status enum instead string

2022-02-11 07:25 UTC, what1s1ove commented on frontend/src/components/common/private-route/private-route.tsx
> +  if (!user) {
```suggestion
  const hasUser = Boolean(user);

  if (!hasUser) {
```

2022-02-11 07:25 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +  const handleOnVisible = (): void => setVisible(!isVisible);
```suggestion
  const handleVisibleChange = (): void => setVisible(!isVisible);
```

2022-02-11 07:25 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +  const [isVisible, setVisible] = useState<boolean>(false);
```suggestion
};

const Header: React.FC<Props> = ({ img, name }) => {
  const [isVisible, setVisible] = useState<boolean>(false);
```
let's avoid it now

2022-02-11 07:25 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +  name: string;
```suggestion
```

2022-02-11 07:25 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +            <span className={styles.profileName}>{name}</span>
```suggestion
            <img src={profile} alt="profile" />
            <span className={styles.profileName}>{tenant?.name}</span>
```
use `tenant` from the store

2022-02-11 07:25 UTC, what1s1ove commented on frontend/src/components/auth/auth.tsx
> +  }
```suggestion
  const hasUser = Boolean(user);
  if (hasUser) {
    return <Navigate to={AppRoute.ROOT} />;
  }
```

2022-02-11 07:55 UTC, what1s1ove commented on frontend/src/components/dashboard/dashboard.tsx
> +import { FC, useEffect } from 'react';
```suggestion
import { FC } from 'react';
```
import from hooks folder

2022-02-11 07:55 UTC, what1s1ove commented on frontend/src/components/auth/auth.tsx
> +import { Navigate } from 'react-router-dom';
```suggestion
import { Navigate } from 'components/common/common';
```

2022-02-11 08:38 UTC, what1s1ove approved these changes

2022-02-11 08:38 UTC, merged