Task/bws20 master sign in
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #3
Opened 2022-02-06 12:42 UTC by sofia0602

2022-02-06 14:01 UTC, what1s1ove requested changes

2022-02-06 14:01 UTC, what1s1ove commented on frontend/src/hooks/use-app-form/use-app-form.hook.ts
> +    mode: 'onBlur',
Actually , we want it on submit (the default behaviour )

2022-02-06 14:01 UTC, what1s1ove commented on frontend/src/components/auth/components/sign-wrapper-form/sign-wrapper-form.tsx
> +  const onSubmit: any = (data: MasterSignInDto) => {
avoid any

2022-02-06 14:01 UTC, what1s1ove commented on frontend/src/common/types/form/form-control-mode.type.ts
> +export { type FormMode };
we don't want it for now

2022-02-06 14:01 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +      <SignWrapperForm></SignWrapperForm>
not sure that we need it here

2022-02-06 14:01 UTC, what1s1ove commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
> +        {/* <p> */}
remove comments

2022-02-06 14:01 UTC, what1s1ove commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
> +          name={getNameOf<MasterSignInDto>('name')}
```suggestion
          name={getNameOf<MasterSignInDto>('email')}
```

2022-02-06 14:01 UTC, what1s1ove commented on shared/src/common/enums/validation/master/master.ts
>  export { MasterSignUpValidationMessage } from './master-sign-up.validation-message';
```suggestion
export { MasterValidationMessage } from './master-sign-up.validation-message';
```
rename filename & enum to the `MasterValidationMessage` and use it for both sign-up and sign-in

2022-02-06 14:01 UTC, what1s1ove commented on shared/src/common/types/master/master-sign-in-dto.type.ts
> +  name: string;
```suggestion
  email: string;
```

2022-02-06 14:01 UTC, what1s1ove commented on shared/src/validation/master/master-sign-in/master-sign-in.validation-schema.ts
> +  [getNameOf<MasterSignInDto>('name')]: Joi.string()
should be an email

2022-02-07 06:10 UTC, what1s1ove commented on frontend/src/components/auth/components/sign-wrapper-form/sign-wrapper-form.tsx
> +import style from './sign-wrapper-form.module.scss';
actually, we don't need this component
with wrapper should be as `frontend/src/components/auth/auth.tsx`component

2022-02-07 07:35 UTC, Yaroslaww-1 requested changes

2022-02-07 07:35 UTC, Yaroslaww-1 commented on frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
> +        </div>
I know that design has it, but you can drop privacy policy

2022-02-07 07:35 UTC, Yaroslaww-1 commented on frontend/src/components/auth/components/sign-wrapper-form/sign-wrapper-form.tsx
> +const SignWrapperForm: React.FC = () => {
Please leave end lines between code components

2022-02-07 07:35 UTC, Yaroslaww-1 commented on frontend/src/components/auth/components/sign-wrapper-form/sign-wrapper-form.tsx
> +export { SignWrapperForm };
```suggestion
import { SignInForm } from '../components';
import { MasterSignInDto } from 'common/types/types';
import { auth as authActions } from 'store/actions';
import { useAppDispatch } from 'hooks/hooks';
import Logo from '../../../../assets/img/logo.svg';

const SignWrapperForm: React.FC = () => {
  const dispatch = useAppDispatch();
  
  const handleSignInSubmit = (payload: MasterSignInDto): void => {
    dispatch(authActions.signIn(payload));
  };
  
  return (
    <>
      <div className={style.wrapper}>
        <img src={Logo} alt="logo" className={style.logo} />
        <SignInForm onSubmit={handleSignInSubmit} />
      </div>
    </>
  );
};

export { SignWrapperForm };
```

2022-02-07 07:53 UTC, what1s1ove requested changes

2022-02-07 07:53 UTC, what1s1ove commented on shared/src/validation/master/master-sign-up/master-sign-up.validation-schema.ts
> +import { MasterSignUpValidationRule } from '~/common/enums/validation/master/master-sign-up-validation-rule.enum';
```suggestion
import { MasterValidationMessage, MasterSignUpValidationRule } from '~/common/enums/enums';
```

2022-02-07 08:37 UTC, what1s1ove approved these changes

2022-02-07 08:38 UTC, merged