Task/bws20 master-sign-in
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #39
Opened 2022-02-12 07:56 UTC by sofia0602

2022-02-12 07:58 UTC, what1s1ove requested changes

2022-02-12 07:58 UTC, what1s1ove commented on shared/src/validation/master/master-sign-in/master-sign-in.validation-schema.ts
> +  MasterSignInValidationRule,
```suggestion
  MasterValidationRule,
```

2022-02-12 07:58 UTC, what1s1ove commented on shared/src/common/enums/enums.ts
>    MasterSignUpValidationRule,
MasterSignUpValidationRule rename to `MasterValidationRule` and keep all rules (sign-in and sign-up) in one place

2022-02-12 09:33 UTC, Yaroslaww-1 commented on shared/src/common/enums/enums.ts
>    MasterSignUpValidationRule,
*`EAMMasterValidationRule`

2022-02-12 10:29 UTC, what1s1ove submitted a review, later dismissed

2022-02-12 14:06 UTC, Yaroslaww-1 requested changes

2022-02-12 14:06 UTC, Yaroslaww-1 commented on backend/src/validation-schemas/master/master.ts
> +export {
File name should be `backend/src/validation-schemas/eam-master/eam-master.ts`

2022-02-12 14:06 UTC, Yaroslaww-1 commented on backend/src/validation-schemas/validation-schemas.ts
> +export { eamMasterSignUp, eamMasterSignIn } from './master/master';
`export { eamMasterSignUp, eamMasterSignIn } from './eam-master/eam-master';`

2022-02-13 07:33 UTC, what1s1ove requested changes

2022-02-13 07:33 UTC, what1s1ove commented on shared/src/validation/eam-master/eam-master-sign-in/eam-master-sign-up.validation-schema copy.ts
> +import * as Joi from 'joi';
is it duplicate ? 🤔

2022-02-13 11:29 UTC, closed without merging