BWS-60: + logout
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #42
Opened 2022-02-12 12:06 UTC by ania-leichenko

2022-02-12 12:32 UTC, what1s1ove requested changes
backend/package-lock.json shouldn't be changed. use the nodejs version from the `readme`

2022-02-12 12:32 UTC, what1s1ove commented on frontend/src/components/app/app.tsx
> +        <Route path={AppRoute.LOG_OUT} element={<LogOut />} />
```suggestion
```
actually you don't need this route at all, you just need to call an action and remove user from the store

2022-02-12 12:32 UTC, what1s1ove commented on frontend/src/common/enums/app/app-route.enum.ts
> +  LOG_OUT = '/logout',
```suggestion
```

2022-02-12 12:32 UTC, what1s1ove commented on frontend/src/components/log-out/log-out.tsx
> +import { FC } from 'react';
remove file

2022-02-12 16:35 UTC, what1s1ove requested changes

2022-02-12 16:35 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +  const handleVisible = (): void => {
```suggestion
  const handleLogout = (): void => {
```

2022-02-12 16:35 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +    navigate(AppRoute.SIGN_IN);
do it in the action

2022-02-13 09:51 UTC, what1s1ove requested changes

2022-02-13 09:51 UTC, what1s1ove commented on backend/package-lock.json
> -{
this file sholdn't be changed

2022-02-13 09:51 UTC, what1s1ove commented on frontend/src/components/common/header/header.tsx
> +    dispatch(logOut(navigate));
```suggestion
  const dispatch = useDispatch();
  const { tenant } = useAppSelector(({ app }) => ({
    tenant: app.tenant,
  }));

  const handleVisibleChange = (): void => setVisible(!isVisible);
  const handleLogout = (): void => {
    dispatch(logOut());
```

2022-02-13 09:51 UTC, what1s1ove commented on frontend/src/store/auth/actions.ts
> +    navigate(AppRoute.SIGN_IN);
```suggestion
    navigate(AppRoute.SIGN_IN);
```
use navigation service (from `extra`)

2022-02-13 14:32 UTC, Donymak approved these changes

2022-02-13 15:21 UTC, what1s1ove approved these changes

2022-02-13 15:21 UTC, merged