Task/bws54 workers table
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #58
Opened 2022-02-14 23:39 UTC by Oleg-feriss

2022-02-15 07:15 UTC, what1s1ove requested changes

2022-02-15 07:15 UTC, what1s1ove commented on frontend/src/store/eam/reducer.ts
> +  workers: null,
```suggestion
  workers: EAMWorkerGetAllResponseDto; // should be EAMWorkerGetAllResponseDto.items
};

const initialState: State = {
  dataStatus: DataStatus.IDLE,
  workers: [],
```

2022-02-15 07:15 UTC, what1s1ove commented on shared/src/common/types/eam-worker/eam-worker-get-all-item-response-dto.type.ts
> +  createdAt: Date;
```suggestion
  createdAt: string;
```

2022-02-15 07:15 UTC, what1s1ove commented on frontend/src/components/eam/components/workers-table/workers-table.tsx
> +  return <Table columns={columns} data={data} title={'Users'} />;
```suggestion
  return <Table columns={columns} data={data} title="Users" />;
```

2022-02-15 07:15 UTC, what1s1ove commented on frontend/src/components/eam/eam.tsx
> +import { eam as workerActions } from 'store/actions';
```suggestion
import { eam as eamActions } from 'store/actions';
```

2022-02-15 07:15 UTC, what1s1ove commented on frontend/src/store/eam/common.ts
> +  GET_WORKERS = 'workers/',
```suggestion
  GET_WORKERS = 'workers/get-all',
```

2022-02-15 07:15 UTC, what1s1ove commented on frontend/src/components/eam/components/workers-table/helpers/get-rows.helper.ts
> +  }
```suggestion
```

2022-02-15 07:15 UTC, what1s1ove commented on frontend/src/components/eam/components/workers-table/helpers/get-rows.helper.ts
> +const getRows = (workers: EAMWorkerGetAllResponseDto | null): Row[] => {
```suggestion
const getRows = (workers: EAMWorkerGetAllResponseDto // should be an array of workers): Row[] => {
```

2022-02-15 08:05 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-02-15 16:01 UTC, what1s1ove commented on frontend/src/components/eam/eam.tsx
> +import { WorkersTable } from './components/workers-table/workers-table';
```suggestion
import { WorkersTable } from './components/components';
```
we already have an import

2022-02-15 16:01 UTC, what1s1ove commented on frontend/src/store/eam/common.ts
> +  GET_WORKERS = 'workers/get-all',
```suggestion
  GET_WORKERS = 'eam/get-all',
```

2022-02-15 18:44 UTC, Oleg-feriss commented
![image](https://user-images.githubusercontent.com/83449323/154127247-aa123e59-bc72-4a0b-9b37-9f68afc750d2.png)

2022-02-15 18:55 UTC, what1s1ove requested changes
add space between tables 

<img width="685" alt="image" src="https://user-images.githubusercontent.com/42296182/154129509-2c4707db-0867-4261-93de-e0f07b03466a.png">

as in design
<img width="751" alt="image" src="https://user-images.githubusercontent.com/42296182/154129643-042eead4-db26-4d6d-b787-20adcb8d7069.png">

2022-02-15 18:55 UTC, Yaroslaww-1 submitted a review, later dismissed

2022-02-16 05:27 UTC, what1s1ove approved these changes

2022-02-16 05:27 UTC, merged