bws-68: + password validation worker
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #62
Opened 2022-02-15 17:52 UTC by sofia0602

2022-02-15 18:21 UTC, what1s1ove requested changes

2022-02-15 18:21 UTC, what1s1ove commented on shared/src/validation/eam-worker/worker-create/worker-create.validation-schema.ts
> +  [getNameOf<EAMWorkerCreateRequestDto>('password')]: Joi.string()
we use this validation for the frontend. there is no `password` field. you need to create a separate one

2022-02-18 10:10 UTC, Yaroslaww-1 requested changes

2022-02-18 10:10 UTC, Yaroslaww-1 commented on backend/src/validation-schemas/validation-schemas.ts
> +export { EamWorkerCreate } from './eam-worker/eam-worker';
```suggestion
export { eamWorkerCreate } from './eam-worker/eam-worker';
```

2022-02-22 07:27 UTC, what1s1ove requested changes

2022-02-22 07:27 UTC, what1s1ove commented on shared/src/common/enums/validation/validation.ts
> +  EAMWorkerValidationMessageBackend,
you don't need to create new enums
you need to add messages and rules to `EAMWorkerValidationMessage`, `EAMWorkerValidationRule`

2022-02-22 07:27 UTC, what1s1ove commented on shared/src/common/enums/validation/worker/eam-worker-create-backend/eam-worker-create-validation-message.ts
> +const EAMWorkerValidationMessageBackend = {
remove this file

2022-02-22 07:27 UTC, what1s1ove commented on shared/src/common/enums/validation/worker/eam-worker-create-backend/eam-worker-create-validation-rule.enum.ts
> +const EAMWorkerValidationRuleBackend = {
remove this file

2022-02-22 07:27 UTC, what1s1ove commented on shared/src/validation/eam-worker/eam-worker-create-backend/eam-worker-create.validation-schema.ts
> +  [getNameOf<EAMWorkerCreateRequestDto>('password')]: Joi.string()
you also need to validate `name`, `groupsIds` and etc (check `EAMWorkerCreateRequestDto` and validate all fields)

2022-02-22 07:27 UTC, what1s1ove commented on shared/src/validation/eam-worker/worker.ts
> +export { eamWorkerCreate } from './eam-worker-create-backend/eam-worker-create.validation-schema';
in this case, you break frontend validation 🤔
you need to keep both

2022-02-22 17:04 UTC, closed without merging