Task/bws24 add server computing
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #67
Opened 2022-02-16 20:22 UTC by tbezrukava

2022-02-16 21:28 UTC, Donymak approved these changes, later dismissed

2022-02-17 07:39 UTC, what1s1ove requested changes

2022-02-17 07:39 UTC, what1s1ove commented on backend/src/common/enums/db/table-name.enum.ts
> +  INSTANCES = 'server_computing.instances',
don't forget about key table

2022-02-18 07:09 UTC, tbezrukava commented
<img width="857" alt="Снимок экрана 2022-02-18 в 08 52 18" src="https://user-images.githubusercontent.com/95911156/154634872-ce5e61cc-c3b5-4e90-8561-2d67d7a55079.png">

2022-02-18 07:17 UTC, what1s1ove requested changes

2022-02-18 07:17 UTC, what1s1ove commented on backend/src/data/seeds/fill-db.ts
> +async function seed(knex: Knex): Promise<void> {
actually this is a part of our application (it isn't a mock data). since it is, it should be a migration instead of a seed

2022-02-18 07:44 UTC, what1s1ove commented on readme.md
> +5. Apply migrations and seeds: `cd backend && npm run migrate:dev`
```suggestion
5. Apply migrations: `cd backend && npm run migrate:dev`
```

2022-02-18 08:48 UTC, what1s1ove approved these changes

2022-02-18 08:55 UTC, Yaroslaww-1 approved these changes

2022-02-18 08:55 UTC, merged