BWS-55: * bug fix
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #73
Opened 2022-02-17 21:02 UTC by bohdanshcherba

2022-02-18 07:48 UTC, what1s1ove requested changes

2022-02-18 07:48 UTC, what1s1ove commented on backend/src/data/repositories/group/group.repository.ts
> +    if (workersIds.length !== 0) {
```suggestion
   const hasWorkersIds = Boolean(workersIds.length )
    if (hasWorkersIds) {
```

2022-02-18 07:48 UTC, what1s1ove commented on shared/src/validation/validation-schemas.ts
> +export { eamGroupCreate, eamGroupConfigurate } from './eam-group/eam-group';
```suggestion
export { eamGroupCreate, eamGroupConfigurate } from './eam-group/eam-group';
```
what are the differences between eamGroupCreate and eamGroupConfigurate?

2022-02-18 07:48 UTC, what1s1ove commented on shared/src/validation/eam-group/eam-group-create/group-create.validation-schema.ts
> +  [getNameOf<EAMGroupCreateRequestDto>('workersIds')]: Joi.array(),
the length of array must be at least 1

2022-02-18 07:48 UTC, what1s1ove commented on shared/src/validation/eam-group/eam-configurate-group/eam-configurate-group.validation-schema.ts
> +  [getNameOf<EAMGroupCreateRequestDto>('workersIds')]: Joi.array(),
the length of array must be at least 1

2022-02-18 07:48 UTC, what1s1ove commented on frontend/src/components/eam-configurate-group/helpers/get-rows.helper.ts
> +    const date = `${el![1]}/${el![2]}/${el![3]} ${el![4]}:${el![5]}`;
```suggestion
```
don't need to pretify date for now

2022-02-18 12:44 UTC, bohdanshcherba commented on shared/src/validation/eam-group/eam-configurate-group/eam-configurate-group.validation-schema.ts
> +  [getNameOf<EAMGroupCreateRequestDto>('workersIds')]: Joi.array(),
User can create a group with no users in it

2022-02-18 12:48 UTC, what1s1ove commented on shared/src/validation/eam-group/eam-configurate-group/eam-configurate-group.validation-schema.ts
> +  [getNameOf<EAMGroupCreateRequestDto>('workersIds')]: Joi.array(),
oh sorry, you're right!

2022-02-19 07:16 UTC, what1s1ove approved these changes

2022-02-19 07:16 UTC, merged