BWS-96: + create permission api
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #74
Opened 2022-02-17 21:57 UTC by bohdanshcherba

2022-02-18 07:04 UTC, what1s1ove submitted a review, later dismissed

2022-02-18 10:05 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-02-18 13:26 UTC, ania-leichenko approved these changes, later dismissed

2022-02-19 07:25 UTC, what1s1ove requested changes

2022-02-19 07:25 UTC, what1s1ove commented on backend/src/api/eam/eam.api.ts
> +    url: `${EAMApiPath.GROUPS}${GroupsApiPath.PERMISSION}`,
```suggestion
    url: `${EAMApiPath.PERMISSION}`,
```

2022-02-19 07:25 UTC, what1s1ove commented on backend/src/services/group/group.service.ts
> +    }
```suggestion
```
we need to handle it by validation

2022-02-19 07:25 UTC, what1s1ove commented on shared/src/validation/eam-group/eam-group-create/group-create.validation-schema.ts
> +    Joi.array().required(),
should be at least 1 permission

2022-02-19 07:26 UTC, what1s1ove requested changes

2022-02-19 07:26 UTC, what1s1ove commented on backend/src/exceptions/permission-select-error/permission-select-error.ts
> +import { HttpCode } from '~/common/enums/enums';
remove this file. handle it by validation

2022-02-19 09:08 UTC, what1s1ove commented on frontend/src/store/eam-group-configurate/actions.ts
> +    permissionIds: [], // will be fix on frontend branch
```suggestion
    permissionIds: [],
```
you also need to handle frontend part in this task

2022-02-19 09:16 UTC, what1s1ove submitted a review, later dismissed

2022-02-19 09:36 UTC, Yaroslaww-1 requested changes

2022-02-19 09:36 UTC, Yaroslaww-1 commented on backend/src/services/permission/permission.service.ts
> +  }
```suggestion
  async getAll(): Promise<EAMPermissionGetAllResponse> {
    return { items: await this.#permissionRepository.getAll() };
  }
```

2022-02-19 11:59 UTC, what1s1ove approved these changes

2022-02-19 12:01 UTC, Yaroslaww-1 approved these changes

2022-02-19 12:01 UTC, merged