BWS-110: + space delete endpoint
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #91
Opened 2022-02-20 18:31 UTC by Donymak

I'm not sure about the return type of delete method in the space service.

2022-02-20 18:45 UTC, what1s1ove requested changes

2022-02-20 18:45 UTC, what1s1ove commented on backend/src/api/bs/bs.api.ts
> +    async handler(req: FastifyRequest<{ Body: BsSpaceDeleteRequestDto }>, rep) {
deleting should be by `:id` in params

2022-02-20 18:45 UTC, what1s1ove commented on backend/src/data/repositories/space/space.repository.ts
> +  async delete({ name }: { name: string }): Promise<number> {
```suggestion
  async delete(id: string): Promise<number> {
```

2022-02-21 14:39 UTC, what1s1ove requested changes

2022-02-21 14:39 UTC, what1s1ove commented on backend/src/api/bs/bs.api.ts
> +      const id = req.query.id;
```suggestion
      const  id } = req.params;
```
should be param

2022-02-21 14:39 UTC, what1s1ove commented on backend/src/data/repositories/space/space.repository.ts
> +  async delete({ id }: { id: string }): Promise<number> {
```suggestion
  async delete(id: string): Promise<number> {
```

2022-02-21 14:39 UTC, what1s1ove commented on backend/src/data/repositories/space/space.repository.ts
> +  async getSpaceById({ id }: { id: string }): Promise<SpaceEntity> {
```suggestion
  async getSpaceById(id: string): Promise<SpaceEntity> {
```

2022-02-21 14:39 UTC, what1s1ove commented on backend/src/services/aws/s3/s3.service.ts
> +  }): Promise<DeleteBucketCommandOutput> {
```suggestion
  public async deleteBucket(name: string): Promise<DeleteBucketCommandOutput> {
```

2022-02-22 14:58 UTC, what1s1ove requested changes

2022-02-22 14:58 UTC, what1s1ove commented on backend/src/api/bs/bs.api.ts
> +      return rep.send({ id: id }).status(HttpCode.OK);
```suggestion
      return rep.send(true).status(HttpCode.OK);
```

2022-02-22 14:58 UTC, what1s1ove commented on shared/src/common/enums/api/bs-api-path.enum.ts
> +  SPACE = '/spaces/:id',
```suggestion
  SPACES_$ID = '/spaces/:id',
```
`$` for dynamic parameters

2022-02-22 15:07 UTC, Yaroslaww-1 approved these changes, later dismissed

2022-02-22 21:04 UTC, closed without merging