BWS-99: + success-messages
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #93
Opened 2022-02-21 15:40 UTC by ania-leichenko

2022-02-21 15:43 UTC, Donymak commented on frontend/src/services/notification/notification.module.scss
> +  border-top: 5px solid #077304;
Add this color to variables

2022-02-21 15:48 UTC, what1s1ove reviewed
attach screenshot please 🙏

2022-02-21 15:52 UTC, junojei commented on frontend/src/services/notification/notification.module.scss
> +  background: center no-repeat url("../../assets/img/check-icon.svg");
```suggestion
  background: center no-repeat url("/assets/img/check-icon.svg");
```

2022-02-21 15:52 UTC, junojei commented on frontend/src/services/notification/notification.module.scss
>    background: center no-repeat url("../../assets/img/attention-icon.svg");
```suggestion
  background: center no-repeat url("/assets/img/attention-icon.svg");
```

2022-02-21 16:50 UTC, what1s1ove commented on frontend/src/services/notification/notification.module.scss
> +  border-top: 5px solid #077304;
agreed

2022-02-21 16:50 UTC, what1s1ove commented on frontend/src/services/notification/notification.module.scss
> +  background: center no-repeat url("../../assets/img/check-icon.svg");
try this way

2022-02-21 16:51 UTC, what1s1ove requested changes

2022-02-21 16:51 UTC, what1s1ove commented on frontend/src/services/notification/notification.module.scss
> +body .successWrapper > div > div:last-child > div[role="button"] > span {
try to use `:global` selector to avoid this

2022-02-22 07:12 UTC, what1s1ove approved these changes

2022-02-22 07:13 UTC, merged