BWS-91: * worker return with array permissions
BinaryStudioAcademy/bsa-winter-2021-2022-bws pull request #97
Opened 2022-02-21 19:40 UTC by bohdanshcherba

2022-02-22 07:12 UTC, what1s1ove requested changes

2022-02-22 07:12 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +        permissions.map((item) => {
map should always return something

2022-02-22 07:12 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +      groupsIds.map(async (item) => {
use reduce instead

2022-02-22 13:44 UTC, what1s1ove requested changes

2022-02-22 13:44 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +    });
```suggestion
    const permissionIds = permissions.reduce((acc, it) => acc.add(it), new Set());
```

2022-02-22 13:44 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +    };
```suggestion
```

2022-02-22 13:44 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +  public async getWorkerPermissions(workerId: string): Promise<Array<string>> {
```suggestion
  public async getWorkerPermissions(workerId: string): Promise<string[]> {
```

2022-02-22 13:44 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +    return Array.from(permissionIds);
do we need to return a name?

2022-02-22 14:56 UTC, what1s1ove requested changes

2022-02-22 14:56 UTC, what1s1ove commented on backend/src/services/worker/worker.entity.ts
> +  public permissions: EAMPermissionGetAllItemResponseDto[] | null;
```suggestion
  public permissions: string[];
```
should be an array of string (names)

2022-02-22 15:09 UTC, bohdanshcherba commented on backend/src/services/worker/worker.entity.ts
> +  public permissions: EAMPermissionGetAllItemResponseDto[] | null;
but workers can be without group

2022-02-23 05:16 UTC, what1s1ove requested changes

2022-02-23 05:16 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +  ): Promise<string[] | null> {
```suggestion
  ): Promise<string[]> {
```

2022-02-23 05:16 UTC, what1s1ove commented on backend/src/data/repositories/worker/worker.repository.ts
> +      return null;
```suggestion
      return [];
```

2022-02-23 05:16 UTC, what1s1ove commented on backend/src/services/worker/worker.entity.ts
> +  public permissions: string[] | null;
```suggestion
  public permissions: string[];
```

2022-02-23 05:16 UTC, what1s1ove commented on backend/src/services/worker/worker.entity.ts
> +    permissions: string[] | null;
```suggestion
    permissions: string[];
```

2022-02-23 05:16 UTC, what1s1ove commented on backend/src/services/worker/worker.entity.ts
> +    permissions: string[] | null;
```suggestion
    permissions: string[];
```

2022-02-23 05:16 UTC, what1s1ove commented on backend/src/services/worker/worker.entity.ts
> +    permissions: string[] | null;
```suggestion
    permissions: string[];
```

2022-02-23 09:08 UTC, what1s1ove approved these changes

2022-02-23 09:08 UTC, merged